AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bibbl.io

  Sample SAM Template for bibbl.io

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: my-table


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SmartNoteTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SnapshotTable
  
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: my-table
      AttributeDefinitions:
        - AttributeName: note_id
          AttributeType: S
        - AttributeName: upload_uri
          AttributeType: S
      KeySchema:
        - AttributeName: note_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "upload_uri"
          KeySchema:
            - AttributeName: "upload_uri"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SmartNoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: smart-notes
      AttributeDefinitions:
        - AttributeName: smart_note_id
          AttributeType: S
        - AttributeName: upload_uri
          AttributeType: S
      KeySchema:
        - AttributeName: smart_note_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "upload_uri"
          KeySchema:
            - AttributeName: "upload_uri"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SnapshotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: snapshots
      AttributeDefinitions:
        - AttributeName: snapshot_id
          AttributeType: S
        - AttributeName: upload_uri
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: smart_note_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "upload_uri"
          KeySchema:
            - AttributeName: "upload_uri"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: user_id
          KeySchema:
            - AttributeName: user_id
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  NotesTableDB:
    Value: !Ref MyTable
    Description: Table name of the newly created DynamoDB table
  SmartNoteTableDB:
    Value: !Ref SmartNoteTable
    Description: Table name of the newly created DynamoDB table 
  SnapshotTableDB:
    Value: !Ref SnapshotTable
    Description: Table name of the newly created DynamoDB table 