version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bibbl"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15ao8arzo1tzz"
s3_prefix = "bibbl"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
