AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'bibbl.io

  Sample SAM Template for bibbl.io

  '
Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        TABLE_NAME: raw-notes
Resources:
  NoteFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_folder/
      Handler: app.note_file_handler
      Runtime: python3.8
      Events:
        NoteFileFunctionApi:
          Type: Api
          Properties:
            Path: /rawnotes
            Method: get
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: NoteFileBucket
            Events:
            - s3:ObjectCreated:*
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonS3FullAccess
  RawNoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: raw-notes
      AttributeDefinitions:
      - AttributeName: note_id
        AttributeType: S
      - AttributeName: s3_upload_object
        AttributeType: S
      KeySchema:
      - AttributeName: note_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: s3_upload_object
        KeySchema:
        - AttributeName: s3_upload_object
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  NoteFileBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
  SmartNoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: smart-notes
      AttributeDefinitions:
      - AttributeName: smart_note_id
        AttributeType: S
      - AttributeName: s3_upload_object
        AttributeType: S
      KeySchema:
      - AttributeName: smart_note_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: s3_upload_object
        KeySchema:
        - AttributeName: s3_upload_object
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SnapShotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: snap-shots
      AttributeDefinitions:
      - AttributeName: snap_shot_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: delivery_date
        AttributeType: S
      KeySchema:
      - AttributeName: snap_shot_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: user_id
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      - IndexName: delivery_date
        KeySchema:
        - AttributeName: delivery_date
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-15ao8arzo1tzz/bibbl/00cf9ec66122de92bad89a85ce1af33e
      Handler: app.test_handler
      Runtime: python3.8
      Events:
        TestApi:
          Type: Api
          Properties:
            Path: /testing
            Method: get
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-table
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SnapDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-15ao8arzo1tzz/bibbl/00cf9ec66122de92bad89a85ce1af33e
      Handler: app.snap_delivery_handler
      Runtime: python3.8
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonS3FullAccess
Outputs:
  TestApi:
    Description: API Gateway endpoint URL for Prod stage for Test function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/testing/
  NoteFileFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - NoteFileFunction
      - Arn
  NotesTableDB:
    Value:
      Ref: RawNoteTable
    Description: Table name of the newly created DynamoDB table